fix: Revoke and pause chart
decentraland/vesting-dashboard pull request #94
Opened 2023-09-05 18:27 UTC by ncomerci

This closes #93

2023-09-07 18:39 UTC, andyesp requested changes

2023-09-07 18:39 UTC, andyesp commented on src/components/Dashboard/Chart/Chart.js
> +      return 'var(--rovoked-color)'
revoked

2023-09-07 18:41 UTC, andyesp commented on src/components/Dashboard/Chart/Chart.js
> +        if (version === ContractVersion.V1) {
both conditions can be in the same if

2023-09-08 14:07 UTC, andyesp commented on src/components/Dashboard/Chart/Chart.js
> +    const getFinalDataPoint = (isRevokedOrPaused) => {
Is this function getting reused? You could write this like
```
const finalDataPoint = isRevokedOrPaused && version === ContractVersion.V1 ? revokeOrPauseDay + 1 : today
```

2023-09-08 14:09 UTC, andyesp approved these changes

2023-09-11 13:54 UTC, 1emu approved these changes

2023-09-11 14:40 UTC, merged